### ISSUE TITLE
Communicating with GPIB device through NI GPIB-ENET/1000 ?

### ISSUE THREAD

**Issue by chmike** [gotmc/visa#1]
Hello, thank you very much for these packages. 

I would like to know what it would require to communicate with a GPIB device connected to a NI GPIB-ENET/1000.
The NI GPIB-ENET/1000 device is an Ethernet gateway for the GPIB bus. 
I can't manage to find any info on the protocol.

**Comment by matthewrankin** [comment]
@chmike I don't have access to a NI GPIB-ENET/1000, and like you I wasn't able to find the protocol definition, so I'm not certain how to communicate with the GPIB-ENET/1000.
